# Dependencies
markdown:            kramdown 
highlighter:         rouge 

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           
#relative_permalinks: true

# Setup
title:               Yateendra
#tagline:             'Sahu'
description:         Yateendra sahu's official website 
url:                 http://yateender.com
baseurl:             
paginate:            15

tagline: A log of everyday life
disqus_shortname: yateendra

# About/contact
author:
  name:              Yateendra 
  url:               http://yateender.com 
  email:             yateendra.sahu@gmail.com 
  googleplus:        https://plus.google.com/+yateendrasahu/

# Timezone
timezone: Asia/Kolkata

# Custom vars
version:             1.0.0

# Custom gems
gems:
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-mentions
    - jemoji
    - jekyll-redirect-from
    - jekyll-feed
   
# jekyll-tagging params
tag_page_layout: blog_by_tag
tag_page_dir: blog/tag
tag_feed_layout: blog_by_tag
tag_feed_dir: blog/tag
tag_permalink_style: pretty
